# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f03f11342ab0d22035cecf2992e309d3a6def16cd834b663927cb065280ba0ed44c0f685a5a569dd0d3c8be77f1b081ccb63aa399b0f19b50857072bcdf077

test:
  secret_key_base: 9063f35c423580507298babd3018edf056f5a3dc50a7ec88b64c3fd90accb2edc916eaa1475b0c2a3781426e5058b0ed2fd24c1b736800f379fa2bee1c50944c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
